export global Theme {
    in property <color> background: #0F1115;
    in property <color> surface: #171A21;
    in property <color> surface_hover: #1D212A;
    in property <color> border: #292E38;
    in property <color> text_primary: #F3F4F6;
    in property <color> text_secondary: #A5AAB5;
    in property <color> text_muted: #6F7683;
    in property <color> accent_hover: #8D72FF;
    in property <color> accent: #7C5CFF;
}